# Kickstart container config file - see https://gitub.com/c7lab/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:8.1"
packages: [php8.1-curl, php8.1-http, php8.1-raphf, php8.1-dom]


command:
  init:
    - "composer update"

  test:
    - "phpunit tests/"