# Kickstart container config file - see https://gitub.com/c7lab/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:8.1"

apache_fallback_resource: "/index.php"

command:
  init:
    - "composer update"

  test:
    - "phpunit tests/"